### ISSUE TITLE
Kaltura Videos Fail to load in Firefox v34.x, v35.x, v36.x, v37.x Mac/PC

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#22]
##### Overview
Nate alerted us to an issue with Kaltura videos not loading when trying to view the page in Firefox.

##### Symptoms
The following error is displayed on page load:
`"The video could not be loaded, either because the server or network failed or because the format is not supported"`

No play button is displayed.

I confirmed the issue on my copy of Firefox on my Mac, and even checked a few versions back (v34, v35, v36) to see if it was an issue with the newest version of Firefox. 

##### Troubleshooting We Have Done:
* We have cleared cache
* I have double checked the project.
* A fresh index.html from the documentation page is used.
* I tested other Kaltura videos
* I verified all expected flavors are available and ready in Kaltura.
* Verified Kaltura videos inside of GVP are playing fine in Chrome and Safari.

##### Console Log (Just in Case)
```
>> "kWidget: Kaltura HTML5 Version: 2.25" jquery.min.js line 2 > eval:47:283

>> downloadable font: OS/2: bad linegap: -64 (font-family: "VideoJS" style:normal weight:normal stretch:normal src index:1) source: https://media.uwex.edu/app/generic_video_player_v3/videoplayer/font/vjs.woff video-js.min.css:8:42

>> HTTP load failed with status 404. Load of media resource https://media.uwex.edu/content/bps/bps_cs290/bps_cs290_course_intro/undefined failed. index.html

>> "VIDEOJS:" "ERROR:" "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" "The video could not be loaded, either because the server or network failed or because the format is not supported." Object { code: 4, message: "The video could not be loaded, either because the server or network failed or because the format is not supported." } combined.video.min.js:8:300
    _logType() combined.video.min.js:8
    vjs.log.error() combined.video.min.js:8
    vjs.Player.prototype.error() combined.video.min.js:9
    vjs.Html5.prototype.eventHandler() combined.video.min.js:10
    vjs.bind/o() combined.video.min.js:8
    vjs.on/o.dispatcher() combined.video.min.js:8
```

**Comment by Lin87** [comment]
404 cannot find the media. Firefox not support the MP4 media Until v39.

**Comment by owlboy** [comment]
![kaltura-webm-flavor](https://cloud.githubusercontent.com/assets/237349/7162079/31a3e5b4-e358-11e4-891d-fb93adedd19c.jpg)

There is a .webm file in the list of available flavors on Kaltura. And always has been.

Is there a reason you chose to not use the .webm video in Kaltura, or use a flash fallback for mp4 playback? Making that choice means that Kaltura videos won't play in Firefox. And we were not aware that this was how things were implemented.

**Comment by Lin87** [comment]
It should be... I cannot access the files. Media server is blocked. @patrick-wirth I'll check ASAP when I get back.

**Comment by owlboy** [comment]
Cool, thank you! Your time responding to these tickets and issues is very appreciated! Thank you!

-Bryan

**Comment by Lin87** [comment]
Found the problem that is causing the error. It is the text file. The code is fine. How did you create the text file? I replace the text file with the same kaltura id and it works. (fyi, @patrick-wirth)

**Comment by Lin87** [comment]
For some reason, Firefox does not like your kaltura text file. Plus, my text file with the same content is only 10B while your is 22B.

**Comment by Lin87** [comment]
Nothing to fix in the code. It just need a real txt file.
