### ISSUE TITLE
DS Logo for Stand Alone Page Desgin

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#23]
Hello,

We need a logo/design for the Data Science program for the Generic Player stand alone page design.
**Example:** https://media.uwex.edu/content/ds/ds700/ds700_interview_sasi_pillay-part_1/

This is a *low priority* issue. Feel free to contact me for help rounding up assets or doing production on this. 

Thanks.

**Comment by Lin87** [comment]
Coming soon this week in v3.3.3 release
