### ISSUE TITLE
Test Result from Patrick

### ISSUE THREAD

**Issue by Lin87** [oel-mediateam/gvp#25]
Version 3.3.3 - Maintenance Update.

**Please check-off each task once you completed or confirmed it.**

- [x] Launch a web browser of your choice.
- [x] Clear browser cache
- [x] Go to https://media.uwex.edu/sandbox/ethan/gvp/sources/scripts/gvp.min.js. Is the version number 3.3.3?
- [x] Go to https://media.uwex.edu/sandbox/ethan/gvp/sources/scripts/jquery.min.js. Is the version number 2.2.0?
- [x] Go to https://media.uwex.edu/sandbox/ethan/gvp/sources/videoplayer/combined.video.min.js. Is the version number: 5.5.3?
- [x] Go to https://media.uwex.edu/sandbox/ethan/gvp/build/.
- [x] Video loads? HTML5?
- [x] In web browser's address bar, append **?intro=1** to the URL and press enter.
- [x] Intro video plays?
- [x] Main video follows and autoplays?
- [x] Remove previous **?intro=1** in the web browser's address bar. Append **?autoplay=1** to the URL and press enter.
- [x] Video autoplays after loading?
- [x] Remove previous **?autoplay=1** in the web browser's address bar. Append **?intro=1&autoplay=1** to the URL and press enter.
- [x] Main video follows and autoplays?
- [x] Video playback is all good?
- [x] Subtitle works?
- [x] Resolution switch is working?

If you have any feedback on the new video player look and feel, please comment below.

- [x] Everything's okay. Sign off. :beers:

**Comment by patrick-wirth** [comment]
Everything worked well!

**Comment by Lin87** [comment]
Thank you!
