### ISSUE TITLE
Download Audio button Missing from GVP Projects

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#29]
Nick is creating some GVP projects that have downloadable audio. And the button for the downloadable audio is not showing up.

**Example Projects:**
https://media.uwex.edu/content/smgt/smgt331_r16/smgt331_ct_cashflow_budget
https://media.uwex.edu/content/smgt/smgt331_r16/smgt331_ct_statement_cashflow

I am not sure if this is a bug, or if it was never implemented for one reason or another. Either way, could you investigate please?

Thanks!

P.S. While you are in there updating, take a peak and make sure that .zip files are a supported type too. GVP should support all of the download types that SB+ does.

**Comment by Lin87** [comment]
The video is from Kaltura. So, I assumed audio was not needed. Does Kaltura convert video to audio? If it can, we can just grab it from Kaltura. Rather than hosted on web server. Thoughts.

Video hosted on web server will display the audio button when available.

ZIP is already there.

**Comment by owlboy** [comment]
Oh! That explains it. I guess no one tried to do this before today.

This means we do need GVP to be updated to look for an MP3 on the web server for Kaltura videos, like the it does for the transcript.

Thanks.

**Comment by Lin87** [comment]
If I remember correct, Patrick said audio is not necessary for Kaltura and future videos.
