### ISSUE TITLE
Stand Alone Page Formatting - Support Two Lines in the Title

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#30]
Minor CSS fix here. Please update the video title so that when it wraps to two lines, the second line displays nicely. Currently it is touching the video.

**Example:**
https://media.uwex.edu/content/hwm/hwm700/hwm700_case-study-core-creative_advice_for_new_professionals/

**Comment by Lin87** [comment]
Fixed. Please double check if you can.
