### ISSUE TITLE
Splash Screen "Title Bar" Updates

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#33]
During the showcase item entry meetings, we discussed some changes to the Generic Player v4 title bar on splash screens.

• Change the bar to black with translucency
• Change the text to white
• Add a button to the far right of the bar for downloadable items - Have it use the same icon and style as the one used in the playback controls.

Students should be able to download these assets without starting the video.

**Comment by Lin87** [comment]
Done. Added
