### ISSUE TITLE
Double Check That All Supporting Assets Work

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#34]
It seemed like there was a possibility that not all the different downloadable assets are appearing in the downloads menu.

Make sure it supports everything that Storybook does.

**Comment by owlboy** [comment]
Well, actually, they are already in there.

Example of it not working for a transcript:
https://media.uwex.edu/content/media/showcase/hwm/hwm700_course_introduction/

**Comment by Lin87** [comment]
Fixed. Array off by one index error.
