### ISSUE TITLE
File Download URLs are not being constructed properly

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#35]
**Example:**
https://media.uwex.edu/content/il/u244370/u244370_course-intro/

The player is constructing incorrect URLs for downloads. It is currently, in this example, removing the `-` from the URL and trying to find a transcript here:
https://media.uwex.edu/content/il/u244370/u244370_course-intro/u244370_courseintro.pdf

**Comment by Lin87** [comment]
Fixed in commit https://github.com/oel-mediateam/gvp/commit/50721e880169e9bad4b9b3f832c5d43c7f9a8f89. Please double check and close issue if resolved.

**Comment by owlboy** [comment]
Seems to be good! 👍
