### ISSUE TITLE
The resulting filename on a downloaded video is a very long collection of Kaltura attributes

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#36]
Download links for Generic Player for Kaltura videos seem to have mutated a bit. The file name I just got for one was this:
`https___cdnapisec.kaltura.com_p_1660872_sp_166087200_playManifest_entryId_0_izmk25cc_flavorId_0_sxp697t5_format_url_protocol_https_a.mp4`

Tested in Safari.

**Comment by Lin87** [comment]
Replicable in all browsers. Fixed. The file name will be grabbed from the URI but defaults to the title on Kaltura if URI is empty.
