### ISSUE TITLE
CC not displaying

### ISSUE THREAD

**Issue by patrick-wirth** [oel-mediateam/gvp#38]
Hi Ethan,

Over the past two weeks, I have noticed that captions won't play in approximately 10% of the videos I add captions to.  In addition, I have noticed that the player icons do not load properly in these same videos.  

Example: https://media.uwex.edu/content/smgt/smgt240_r19/smgt240_lesson8_overview/index.html

![Screen Shot 2019-08-26 at 9 44 36 AM](https://user-images.githubusercontent.com/5795703/63699308-28a7c580-c7e6-11e9-8160-acb001e08107.png)

**Comment by Lin87** [comment]
Do you have the link to this video? Thanks!

**Comment by patrick-wirth** [comment]
I added it to the post.
